import {Globe2,ShoppingBag,Code2,Layers3,Bot,GraduationCap} from 'lucide-react';
export const services=[
{icon:Globe2,title:'Websites with presence.',sub:'Business websites & personal brands',text:'A clear story, a distinctive design and a fast, responsive website that helps people understand your business.',items:['Business websites','Portfolios & personal brands','Landing pages','Website redesign']},
{icon:ShoppingBag,title:'Stores built to sell.',sub:'E-commerce & digital storefronts',text:'Thoughtful product discovery, mobile shopping and a straightforward path from browsing to checkout.',items:['Product catalogs','Cart & checkout','Payment integrations','Inventory & admin tools']},
{icon:Code2,title:'Products that do more.',sub:'SaaS & custom applications',text:'From a focused internal tool to a customer-facing platform, built around the workflows you actually need.',items:['SaaS dashboards','Authentication & roles','APIs & databases','Booking systems']},
{icon:Layers3,title:'Experiences you can feel.',sub:'3D websites & creative development',text:'Interactive product scenes and carefully paced motion that bring an idea to life across devices.',items:['Three.js & WebGL','Interactive product demos','Scroll storytelling','Motion design']},
{icon:Bot,title:'Intelligence, put to work.',sub:'AI integration & automation',text:'Connect AI to useful tasks: answering questions, assisting research and reducing repetitive work.',items:['AI assistants','Agent workflows','AI-powered interfaces','Workflow automation']},
{icon:GraduationCap,title:'A better way to learn.',sub:'Education & institute platforms',text:'Accessible learning experiences and practical tools for institutes, students and administrators.',items:['Course websites','Student dashboards','Certificate systems','QR verification']}];
export const work=[
{id:'physics',name:'The Living Physics Book',category:'Education',tag:'LIVE PROJECT',description:'An interactive physics book with chapters, formulas, notebook tools and offline support.',visual:'physics',url:'https://semesterone.vercel.app/',highlights:['53 learning topics','Offline-ready','Notes & progress'],details:'A B.Sc. learning experience pairing formal definitions with interactive explanations. Explore 53 topics across four chapters, save notes and install the book for offline learning.'},
{id:'vmart',name:'V-Mart Siwan — Edition Two',category:'E-commerce',tag:'DEPLOYED DEMO',description:'A fashion storefront with collection browsing, product discovery and a personal Style Studio.',visual:'vmart',url:'https://vmartsiwaneditiontwo.vercel.app/',highlights:['Category browsing','Wishlist + bag','Style Studio'],details:'A deployed V-Mart Siwan storefront build featuring category browsing, product pages, wishlist controls, a shopping-bag interface and Style Studio. Selected for its editorial presentation and richer shopping interface. Orders and payments are unavailable in this demo; this portfolio does not claim an official V-Mart commission.'},
{id:'bit',name:'Bharat Institute of Technology',category:'Education',tag:'LIVE PROJECT',description:'The BIT Ghosi website: course discovery, an immersive learning-themed design and certificate tools.',visual:'bit',url:'https://bitghosi.vercel.app/',highlights:['18 proposed courses','Certificate tools','QR verification'],details:'An institute website built for BIT Ghosi, with 18 proposed course pathways, detailed course exploration, an interactive learning-themed hero and certificate studio and verification sections. Programme fees, schedules and availability are subject to confirmation by the institute.'}];
export const options=[{name:'Business Website',base:10000},{name:'Portfolio',base:10000},{name:'Landing Page',base:10000},{name:'E-Commerce',base:25000},{name:'Educational Website',base:15000},{name:'SaaS',base:40000},{name:'3D Website',base:35000},{name:'Custom Platform',base:50000}];
export const extras=[{name:'Animation',price:3000},{name:'3D experience',price:15000},{name:'Admin dashboard',price:12000},{name:'Payments',price:10000},{name:'Authentication',price:8000},{name:'Database',price:8000},{name:'AI integration',price:15000},{name:'CMS',price:8000},{name:'Booking',price:8000}];
export const plans=[{name:'Starter',cost:'₹10,000',desc:'A strong first impression.',items:['Up to 5 responsive pages','Custom visual direction','Contact inquiry flow','Basic SEO & social links','Deployment assistance']},{name:'Growth',cost:'₹25,000',desc:'More room for your next chapter.',items:['Expanded website scope','Premium motion & interactions','CMS and content workflows','Analytics setup','Performance refinement']},{name:'Custom',cost:'Let’s talk',desc:'For something beyond the ordinary.',items:['E-commerce & SaaS platforms','Interactive 3D experiences','AI tools & automation','Custom APIs & integrations','Scoped architecture & handover']}];
export const faqs=[['What does a ₹10,000 website include?','The Starter scope covers a responsive website of up to five pages, a contact inquiry flow, basic search metadata, social links and deployment assistance. We confirm the exact scope before work begins.'],['How long does a project take?','Timing depends on the pages, functionality and availability of your content. We agree on milestones and a delivery schedule after reviewing your brief.'],['Can you improve my existing website?','Yes. We can review its structure, design and performance, then agree on a focused redesign or a fuller rebuild.'],['Do you build AI and 3D experiences?','Yes. AI integrations, workflow automation and interactive 3D are available as part of a custom project. We choose the approach around your goals and the devices your visitors use.'],['Are hosting and ongoing tools included?','Domain registration, hosting, payment-provider charges and paid third-party tools are scoped separately. We explain the expected recurring costs before choosing those services.'],['What happens after launch?','We provide the agreed handover and deployment support. Ongoing maintenance, updates and additional features can be arranged separately.']];
